version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "[Install] Installing..."
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 211125364313.dkr.ecr.ap-southeast-1.amazonaws.com/app1
  build:
    commands:
      - echo "[Build] Building Spring Boot application with mvn..."
      - mvn clean install
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t app1:latest .
      - docker tag app1:latest 211125364313.dkr.ecr.ap-southeast-1.amazonaws.com/app1:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 211125364313.dkr.ecr.ap-southeast-1.amazonaws.com/app1:latest